2025-01-18 14:33:05 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:09 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:13 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:18 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:23 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:28 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:33 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:38 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 14:33:43 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_el_syst_par" не существует
2025-01-18 15:32:31 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:32:35 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:32:40 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:32:45 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:32:50 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:32:55 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:00 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:05 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:10 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:16 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:20 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:25 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:31 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:35 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:40 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:46 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:50 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:33:55 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:00 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:05 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:10 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:15 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:20 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:25 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:30 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:35 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:40 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-18 15:34:45 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_electric_system_parameters" в таблице "transports_data" не существует
2025-01-21 09:49:32 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:49:37 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:49:42 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:49:47 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:49:51 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:49:55 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:49:59 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:50:03 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:50:07 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:50:11 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:50:15 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:50:19 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:50:23 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:07 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:11 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:15 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:19 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:23 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:27 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:31 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:35 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:39 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:43 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:47 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:51 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:55 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:53:59 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:03 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:07 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:11 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:15 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:19 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:24 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:29 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:34 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:39 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:44 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:49 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:54 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:54:59 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:55:04 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:55:09 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:55:14 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:55:19 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:55:24 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
2025-01-21 09:55:29 [error]: Ошибка при сохранении данных транспорта в TransportsData или обновлении received_count: столбец "id_transport" в таблице "transports_data" не существует
